# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.setWindowModality(QtCore.Qt.NonModal)
        widget.resize(1000, 804)
        widget.setMinimumSize(QtCore.QSize(1000, 0))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        widget.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widget.setWindowIcon(icon)
        widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        widget.setStyleSheet("background-color:#293b5f;")
        widget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.loginTitle = QtWidgets.QLabel(widget)
        self.loginTitle.setGeometry(QtCore.QRect(0, 190, 1000, 121))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginTitle.sizePolicy().hasHeightForWidth())
        self.loginTitle.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(40)
        font.setUnderline(False)
        self.loginTitle.setFont(font)
        self.loginTitle.setStyleSheet("color: #dbe6fd;\n"
                                      "width: 100%;")
        self.loginTitle.setTextFormat(QtCore.Qt.PlainText)
        self.loginTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.loginTitle.setObjectName("loginTitle")
        self.logo = QtWidgets.QLabel(widget)
        self.logo.setGeometry(QtCore.QRect(200, 40, 600, 150))
        self.logo.setMaximumSize(QtCore.QSize(16777215, 167772))
        font = QtGui.QFont()
        font.setFamily("Castellar")
        font.setPointSize(-1)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.logo.setFont(font)
        self.logo.setMouseTracking(False)
        self.logo.setStyleSheet("color: #dbe6fd;\n"
                                "font-size: 100px;")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.verticalLayoutWidget = QtWidgets.QWidget(widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(140, 340, 691, 341))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.username = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.username.setFont(font)
        self.username.setStyleSheet("margin-left:40px;\n"
                                    "margin-right:40px;\n"
                                    "color: grey;\n"
                                    "border: 1px solid grey;\n"
                                    "border-radius:20px;\n"
                                    "border-bottom:3px solid white;\n"
                                    "padding: 5px;\n"
                                    "padding-left: 15px;")
        self.username.setObjectName("username")
        self.verticalLayout.addWidget(self.username)
        self.password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.password.setFont(font)
        self.password.setStyleSheet("margin-left:40px;\n"
                                    "margin-right:40px;\n"
                                    "color: grey;\n"
                                    "border: 1px solid grey;\n"
                                    "border-radius:20px;\n"
                                    "border-bottom:3px solid white;\n"
                                    "padding: 5px;\n"
                                    "padding-left: 15px;")
        self.password.setObjectName("password")
        self.verticalLayout.addWidget(self.password)
        self.loginButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.loginButton.setStyleSheet("border: 4px solid \'#2541b2\';\n"
                                       " border-radius: 45px;\n"
                                       "font-size: 35px;\n"
                                       "color: \'white\';\n"
                                       "padding: 25px 0;\n"
                                       " margin: 10px 200px;")
        self.loginButton.setObjectName("loginButton")
        self.verticalLayout.addWidget(self.loginButton)
        self.forgetPassword = QtWidgets.QLabel(widget)
        self.forgetPassword.setGeometry(QtCore.QRect(50, 710, 171, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.forgetPassword.setFont(font)
        self.forgetPassword.setObjectName("forgetPassword")
        self.signUpLabel = QtWidgets.QLabel(widget)
        self.signUpLabel.setGeometry(QtCore.QRect(510, 710, 231, 30))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.signUpLabel.setFont(font)
        self.signUpLabel.setObjectName("signUpLabel")
        self.forgetPasswordBtn = QtWidgets.QPushButton(widget)
        self.forgetPasswordBtn.setGeometry(QtCore.QRect(340, 710, 150, 30))
        self.forgetPasswordBtn.setStyleSheet("border: 1px solid \'#2541b2\';\n"
                                             "background-color: rgb(85, 170, 255);\n"
                                             " border-radius: 5px;\n"
                                             "font-size: 12px;\n"
                                             "color: \'black\';")
        self.forgetPasswordBtn.setObjectName("forgetPasswordBtn")
        self.signUpBtn = QtWidgets.QPushButton(widget)
        self.signUpBtn.setGeometry(QtCore.QRect(800, 710, 150, 30))
        self.signUpBtn.setStyleSheet("border: 1px solid \'#2541b2\';\n"
                                     "background-color: rgb(170, 255, 255);\n"
                                     " border-radius: 5px;\n"
                                     "font-size: 12px;\n"
                                     "color: \'black\';")
        self.signUpBtn.setObjectName("signUpBtn")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Hayatul Islamiya SIS"))
        self.loginTitle.setText(_translate("widget", "Log in"))
        self.logo.setText(_translate("widget", "Hayatul"))
        self.username.setPlaceholderText(_translate("widget", "Username"))
        self.password.setPlaceholderText(_translate("widget", "Password"))
        self.loginButton.setText(_translate("widget", "login"))
        self.forgetPassword.setText(_translate("widget", "Forget Password?"))
        self.signUpLabel.setText(_translate("widget", "Don\'n have an account?"))
        self.forgetPasswordBtn.setText(_translate("widget", "reset password"))
        self.signUpBtn.setText(_translate("widget", "Sign up"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    widget = QtWidgets.QWidget()
    ui = Ui_widget()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec_())
